In [1]:
from cpclasses import *
import torch



In [2]:
data_flat = np.loadtxt('pos_e1_e2_e3_1000.txt')
print(data_flat[0])

data_in_file = [[d[:24].reshape(12,2),d[24],d[25],d[26]] for d in data_flat]
print(data_in_file[0])

[  5.055454   4.291927   4.100563   2.266553   4.693256   5.853959
   4.157208   7.436068   4.908682   6.813956   5.612765   6.151167
   6.329216   5.468951   6.029016   4.512863   5.38903    5.203717
   6.68344    3.807901   3.956929   6.478274   3.789781   5.511435
 -34.298077 -32.365418 -33.880081]
[array([[5.055454, 4.291927],
       [4.100563, 2.266553],
       [4.693256, 5.853959],
       [4.157208, 7.436068],
       [4.908682, 6.813956],
       [5.612765, 6.151167],
       [6.329216, 5.468951],
       [6.029016, 4.512863],
       [5.38903 , 5.203717],
       [6.68344 , 3.807901],
       [3.956929, 6.478274],
       [3.789781, 5.511435]]), -34.298077, -32.365418, -33.880081]


In [3]:
n_neurons = 8
n_hidden = 3

activation = torch.nn.ReLU()

layers = []
layers.append(torch.nn.Linear(1, n_neurons))
layers.append(activation)
for i in range(n_hidden):
    layers.append(torch.nn.Linear(n_neurons, n_neurons))
    layers.append(activation)

layers.append(torch.nn.Linear(n_neurons, 1))
model = torch.nn.Sequential(*layers)

In [35]:
CLN = CustomLinearNetwork(1,8, 'relu')


CN2 = CustomNetwork2()

NN = torch.nn.Sequential(
    torch.nn.Linear(1, 8),
    torch.nn.ReLU(),
    torch.nn.Linear(8, 8),
    torch.nn.ReLU(),
    torch.nn.Linear(8, 1)
)


xs = torch.linspace(0,1,10).view(-1,1)

print(CLN(xs))
print(CN2(xs))
print(NN(xs).flatten())

tensor([-0.3727, -0.3498, -0.3269, -0.3040, -0.2811, -0.2690, -0.2607, -0.2541,
        -0.2585, -0.2628], grad_fn=<ViewBackward0>)
tensor([-0.4380, -0.4417, -0.4448, -0.4476, -0.4505, -0.4534, -0.4570, -0.4606,
        -0.4611, -0.4616], grad_fn=<ViewBackward0>)
tensor([-0.1705, -0.1731, -0.1758, -0.1813, -0.1880, -0.1947, -0.2015, -0.2082,
        -0.2149, -0.2218], grad_fn=<ViewBackward0>)
